name: section_sniper
description: This is an app to help students at Texas A&M University get the coureses they want.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.4
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.16.0
  provider: ^3.1.0
  http: ^0.12.1
  firebase_messaging: ^6.0.0
  permission_handler: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

